"""sync_comments_and_types

Revision ID: f55e185ad212
Revises: 20260430_strategy_swing_phase0
Create Date: 2026-04-30 21:36:11.920984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55e185ad212'
down_revision: Union[str, Sequence[str], None] = '20260430_strategy_swing_phase0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_analysis', 'strategy',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               type_=sa.String(length=20),
               comment='策略标识：short / swing',
               existing_nullable=False)
    op.create_table_comment(
        'ai_analysis',
        'Claude AI 分析结果（按 strategy 隔离），永久保留',
        existing_comment='Claude AI 分析结果（Phase 3 启用），永久保留',
        schema=None
    )
    op.alter_column('filter_score_daily', 'strategy',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               type_=sa.String(length=20),
               comment='策略标识：short / swing',
               existing_nullable=False)
    op.create_table_comment(
        'filter_score_daily',
        '规则层维度逐行打分表（按 strategy 隔离，永久保留供回测）',
        existing_comment='规则层 5 维度逐行打分表（永久保留，供回测）',
        schema=None
    )
    op.alter_column('hot_money_detail', 'hm_orgs',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False,
               comment='关联营业部（聚合展示字段；缺失用空串兜底）',
               existing_comment='关联营业部，从 hm_list 冗余')
    op.create_table_comment(
        'hot_money_detail',
        '每日游资交易明细（按 date×stock×游资 聚合，营业部用 ; 拼接到 hm_orgs）',
        existing_comment='每日游资交易明细，LhbFilter 席位身份加权辅助',
        schema=None
    )
    op.create_table_comment(
        'lhb',
        '龙虎榜汇总（Tushare top_list），席位明细见 lhb_seat_detail',
        existing_comment='龙虎榜（Tushare top_list + top_inst），LhbFilter 打分源',
        schema=None
    )
    op.alter_column('selection_result', 'strategy',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               type_=sa.String(length=20),
               comment='策略标识：short / swing',
               existing_nullable=False)
    op.alter_column('selection_result', 'ai_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='AI 层综合分 0-100；跳过 AI 或调用失败时为 NULL',
               existing_comment='AI 层综合分 0-100；Phase 3 前为 NULL',
               existing_nullable=True)
    op.alter_column('selection_result', 'final_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='最终分；AI 缺失时等于 rule_score，否则按综合层权重融合 rule_score 与 ai_score',
               existing_comment='最终分；Phase 1 = rule_score，Phase 3 起 = rule*0.6 + ai*0.4',
               existing_nullable=False)
    op.create_table_comment(
        'selection_result',
        '最终选股 TOP N 结果（按 strategy 隔离，作为报告与回测主数据源）',
        existing_comment='最终选股 TOP N 结果（永久保留，作为每日报告与回测的主数据源）',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'selection_result',
        '最终选股 TOP N 结果（永久保留，作为每日报告与回测的主数据源）',
        existing_comment='最终选股 TOP N 结果（按 strategy 隔离，作为报告与回测主数据源）',
        schema=None
    )
    op.alter_column('selection_result', 'final_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='最终分；Phase 1 = rule_score，Phase 3 起 = rule*0.6 + ai*0.4',
               existing_comment='最终分；AI 缺失时等于 rule_score，否则按综合层权重融合 rule_score 与 ai_score',
               existing_nullable=False)
    op.alter_column('selection_result', 'ai_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='AI 层综合分 0-100；Phase 3 前为 NULL',
               existing_comment='AI 层综合分 0-100；跳过 AI 或调用失败时为 NULL',
               existing_nullable=True)
    op.alter_column('selection_result', 'strategy',
               existing_type=sa.String(length=20),
               server_default=sa.text("'short'::character varying"),
               type_=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='策略标识：short / swing',
               existing_nullable=False)
    op.create_table_comment(
        'lhb',
        '龙虎榜（Tushare top_list + top_inst），LhbFilter 打分源',
        existing_comment='龙虎榜汇总（Tushare top_list），席位明细见 lhb_seat_detail',
        schema=None
    )
    op.create_table_comment(
        'hot_money_detail',
        '每日游资交易明细，LhbFilter 席位身份加权辅助',
        existing_comment='每日游资交易明细（按 date×stock×游资 聚合，营业部用 ; 拼接到 hm_orgs）',
        schema=None
    )
    op.alter_column('hot_money_detail', 'hm_orgs',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True,
               comment='关联营业部，从 hm_list 冗余',
               existing_comment='关联营业部（聚合展示字段；缺失用空串兜底）')
    op.create_table_comment(
        'filter_score_daily',
        '规则层 5 维度逐行打分表（永久保留，供回测）',
        existing_comment='规则层维度逐行打分表（按 strategy 隔离，永久保留供回测）',
        schema=None
    )
    op.alter_column('filter_score_daily', 'strategy',
               existing_type=sa.String(length=20),
               server_default=sa.text("'short'::character varying"),
               type_=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='策略标识：short / swing',
               existing_nullable=False)
    op.create_table_comment(
        'ai_analysis',
        'Claude AI 分析结果（Phase 3 启用），永久保留',
        existing_comment='Claude AI 分析结果（按 strategy 隔离），永久保留',
        schema=None
    )
    op.alter_column('ai_analysis', 'strategy',
               existing_type=sa.String(length=20),
               server_default=sa.text("'short'::character varying"),
               type_=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='策略标识：short / swing',
               existing_nullable=False)
    # ### end Alembic commands ###
